### ISSUE TITLE
Choose sensible defaults for Mesos CPU/RAM/instances

### ISSUE THREAD

**Issue by JayH5** [praekelt/mc2#52]
It's a pain typing in 0.1, 128, 1 over and over again.

**Comment by JayH5** [comment]
Defaults are set. They just do not reflect in the UI form.

**Comment by smn** [comment]
![mission_control](https://cloud.githubusercontent.com/assets/1065/17521597/28ff9854-5e54-11e6-8e20-6dc42b3ab317.jpg)

They do nowadays.
