### ISSUE TITLE
sometimes orgs go missing in the drop down

### ISSUE THREAD

**Issue by miltontony** [praekelt/mc2#75]
![odd](https://cloud.githubusercontent.com/assets/623417/14343897/3466d6e2-fca4-11e5-8b1e-f7a8b52f53fe.gif)

**Comment by smn** [comment]
@miltontony is this still an issue?

**Comment by miltontony** [comment]
@smn Not quite...you just need to scroll, but there might be something better we can do in the UI to make it more obvious that you can scroll, or just make the drop down that much longer.

**Comment by miltontony** [comment]
fixed in #131
